### ISSUE TITLE
Exercism.found not a registered configuration when submitting exercise

### ISSUE THREAD

**Issue by BNAndras** [exercism/vscode-exercism-cli#6]
```
[Extension Host] [exec] exercism version
console.ts:137 [Extension Host] [exec] out for exercism version exercism version 3.0.13

log.ts:313   ERR Unable to write to Workspace Settings because exercism.found is not a registered configuration.: Error: Unable to write to Workspace Settings because exercism.found is not a registered configuration.
    at D.toConfigurationEditingError (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:12042)
    at D.validate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:15063)
    at D.doWriteConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8371)
    at Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8227)
    at T.consume (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:16088)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:15903
    at new Promise (<anonymous>)
    at T.queue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:87:15827)
    at D.writeConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8196)
    at O.writeConfigurationValue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:43156)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:26294
    at Array.map (<anonymous>)
    at O.updateValue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:26282)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 [exec] exercism version
[exec] out for exercism version exercism version 3.0.13
```

**Comment by BNAndras** [comment]
This appears to be an issue when using a keybinding for submitting an exercise. After I tried this, I was able to see the command for submitting an exercise in the command palette, and selecting it there worked fine.

**Comment by SleeplessByte** [comment]
Does this still happen in `0.2.0` or `0.2.1`? The `exercism.found` setting is not being used anymore I think.

**Comment by SleeplessByte** [comment]
After looking into this I can work around it in `0.2.2`. Will be published in a bit!
